import { z } from 'zod';

export const SETTINGS_KEYS = [
  'ui:sidebarMode',
  'ui:sidebarOpen',
  'ui:theme',
  'ui:inheritedColorEnabled',
  'ui:indentationGuides',
  'ui:fontFamily',
  'ui:fontSize',
  'ui:compactDensity',
  'mru:scope',
  'search:engine',
  'search:customUrl',
  'search:suggestions',
  'startup:restore-tabs',
  'startup:page',
  'startup:custom-url',
  'updates:auto-check',
  'privacy:block-third-party-cookies',
  'privacy:do-not-track',
  'privacy:dns-over-https',
  'privacy:doh-provider',
  'addressbar:strip-tracking',
  'ui:custom-themes',
  'ui:custom-css',
  'reader:font-family',
  'reader:font-size',
  'reader:line-height',
  'reader:theme',
  'reader:always-on-domains',
  'search:custom-engines',
  'notifications:permissions',
  'notifications:silence-rules',
  'notifications:panel-open',
  'extensions:disabled',
  'mru:behavior',
  'tabs:last-tab-action',
  'tabs:confirm-close-window',
  'tabs:activate-new',
  'tabs:discard-enabled',
  'tabs:discard-timeout',
  'tabs:discard-audio',
  'tabs:discard-forms',
  'tabs:discard-pinned',
  'tabs:discard-whitelist',
  'tabs:new-tab-page',
  'tabs:new-tab-custom-url',
  'tabs:auto-collapse-folders',
  'ui:glassmorphism',
  'ui:glassmorphism-intensity',
  'ui:glassmorphism-opacity',
  'previews:enabled',
  'previews:resolution',
  'tabs:discard-permanent-whitelist',
  'tabs:discard-workspace-whitelists',
  'tabs:discard-folder-whitelists',
  'filepicker:enabled',
  'filepicker:recent-limit',
  'glance:enabled',
  'glance:modifier',
  'glance:width',
  'glance:height',
  'media:widget-enabled',
  'media:tab-indicator',
  'history:enabled',
  'history:retention',
  'workspaces:switch-modifier',
  'tabs:discard-on-workspace-switch',
  'ui:sidebarWidth',
  'gestures:enabled',
  'gestures:show-trail',
  'gestures:min-segment-px',
  'gestures:bindings',
  'adblocker:enabled',
  'adblocker:active-lists',
  'adblocker:custom-lists',
  'vault:autofill-enabled',
  'bug-snapshot:include-network',
  'aparejo:adblocker:enabled',
  'aparejo:cookies:enabled',
  'urlbar:icon-config',
  'titlebar:icon-visibility',
  'sync:recovery-card-saved',
  'sync:disabled-categories',
  'ui:sidebar-newtab-pos',
  'favorites:view-mode',
  'sidebar:tab-preview-delay',
  'notifications:display-mode',
] as const;

export type SettingsKey = (typeof SETTINGS_KEYS)[number];

export const settingsKeySchema = z.enum(SETTINGS_KEYS);

export const SETTINGS_SCOPES = ['global', 'profile'] as const;
export type SettingsScope = (typeof SETTINGS_SCOPES)[number];
export const settingsScopeSchema = z.enum(SETTINGS_SCOPES);

/**
 * Scope por defecto de cada clave conocida. Refleja la decisión del Prompt 6:
 * los ajustes que afectan al aspecto y comportamiento del perfil viven en
 * profile.db; los que son del usuario o del binario van a vela.db.
 *
 * El handler IPC cae a este map cuando el caller no proporciona `scope`
 * explícito en el payload — así el código existente del renderer no necesita
 * pasarlo a menos que quiera leer un setting del scope contrario.
 */
export const SETTINGS_DEFAULT_SCOPE: Record<SettingsKey, SettingsScope> = {
  'ui:sidebarMode': 'profile',
  'ui:sidebarOpen': 'profile',
  'ui:theme': 'profile',
  'ui:inheritedColorEnabled': 'profile',
  'ui:indentationGuides': 'profile',
  'ui:fontFamily': 'profile',
  'ui:fontSize': 'profile',
  'ui:compactDensity': 'profile',
  'mru:scope': 'profile',
  'search:engine': 'profile',
  'search:customUrl': 'profile',
  'search:suggestions': 'profile',
  'startup:restore-tabs': 'profile',
  'startup:page': 'profile',
  'startup:custom-url': 'profile',
  'updates:auto-check': 'global',
  'privacy:block-third-party-cookies': 'profile',
  'privacy:do-not-track': 'profile',
  'privacy:dns-over-https': 'profile',
  'privacy:doh-provider': 'profile',
  'addressbar:strip-tracking': 'profile',
  'ui:custom-themes': 'profile',
  'ui:custom-css': 'profile',
  'reader:font-family': 'profile',
  'reader:font-size': 'profile',
  'reader:line-height': 'profile',
  'reader:theme': 'profile',
  'reader:always-on-domains': 'profile',
  'search:custom-engines': 'profile',
  'notifications:permissions': 'profile',
  'notifications:silence-rules': 'profile',
  'notifications:panel-open': 'profile',
  'extensions:disabled': 'profile',
  'mru:behavior': 'profile',
  'tabs:last-tab-action': 'profile',
  'tabs:confirm-close-window': 'profile',
  'tabs:activate-new': 'profile',
  'tabs:discard-enabled': 'profile',
  'tabs:discard-timeout': 'profile',
  'tabs:discard-audio': 'profile',
  'tabs:discard-forms': 'profile',
  'tabs:discard-pinned': 'profile',
  'tabs:discard-whitelist': 'profile',
  'tabs:new-tab-page': 'profile',
  'tabs:new-tab-custom-url': 'profile',
  'tabs:auto-collapse-folders': 'profile',
  'ui:glassmorphism': 'profile',
  'ui:glassmorphism-intensity': 'profile',
  'ui:glassmorphism-opacity': 'profile',
  'previews:enabled': 'profile',
  'previews:resolution': 'profile',
  'tabs:discard-permanent-whitelist': 'profile',
  'tabs:discard-workspace-whitelists': 'profile',
  'tabs:discard-folder-whitelists': 'profile',
  'filepicker:enabled': 'profile',
  'filepicker:recent-limit': 'profile',
  'glance:enabled': 'global',
  'glance:modifier': 'global',
  'glance:width': 'global',
  'glance:height': 'global',
  'media:widget-enabled': 'global',
  'media:tab-indicator': 'global',
  'history:enabled': 'profile',
  'history:retention': 'profile',
  'workspaces:switch-modifier': 'global',
  'tabs:discard-on-workspace-switch': 'profile',
  'ui:sidebarWidth': 'profile',
  'gestures:enabled': 'global',
  'gestures:show-trail': 'global',
  'gestures:min-segment-px': 'global',
  'gestures:bindings': 'global',
  'adblocker:enabled': 'profile',
  'adblocker:active-lists': 'profile',
  'adblocker:custom-lists': 'profile',
  'vault:autofill-enabled': 'profile',
  'bug-snapshot:include-network': 'profile',
  'aparejo:adblocker:enabled': 'profile',
  'aparejo:cookies:enabled': 'profile',
  'urlbar:icon-config': 'profile',
  'titlebar:icon-visibility': 'profile',
  'sync:recovery-card-saved': 'profile',
  'sync:disabled-categories': 'profile',
  'ui:sidebar-newtab-pos': 'profile',
  'favorites:view-mode': 'profile',
  'sidebar:tab-preview-delay': 'profile',
  'notifications:display-mode': 'profile',
};

export const settingsGetInputSchema = z.object({
  key: settingsKeySchema,
  scope: settingsScopeSchema.optional(),
});

export const settingsSetInputSchema = z.object({
  key: settingsKeySchema,
  value: z.unknown(),
  scope: settingsScopeSchema.optional(),
});

export const settingsGetAllInputSchema = z.object({
  scope: settingsScopeSchema.optional(),
});
